## Gracias a Alvaro Fuenzalida (@a_fuenzalidag) y Gonzalo Oyanedel (@goyanedelvial) por su invaluable ayuda
## armando este script.



library(jsonlite)
library(xlsx)
library(dplyr)


dist01 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6001.json")
dist02 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6002.json")
dist03 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6003.json")
dist04 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6004.json")
dist05 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6005.json")
dist06 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6006.json")
dist07 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6007.json")
dist08 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6008.json")
dist09 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6009.json")
dist10 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6010.json")
dist11 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6011.json")
dist12 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6012.json")
dist13 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6013.json")
dist14 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6014.json")
dist15 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6015.json")
dist16 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6016.json")
dist17 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6017.json")
dist18 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6018.json")
dist19 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6019.json")
dist20 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6020.json")
dist21 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6021.json")
dist22 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6022.json")
dist23 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6023.json")
dist24 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6024.json")
dist25 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6025.json")
dist26 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6026.json")
dist27 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6027.json")
dist28 <- fromJSON(txt="http://servelelecciones.cl/data/elecciones_diputados/computo/distritos/6028.json")

tabla_dist01<- data.frame(dist01$data$sd[[1]]$sd[[1]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[2]]$sd[[1]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[2]]$sd[[2]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[2]]$sd[[3]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[3]]$sd[[1]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[3]]$sd[[2]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[3]]$sd[[3]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[4]]$sd[[1]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[5]]$sd[[1]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[5]]$sd[[2]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[5]]$sd[[3]])
tabla_dist01<- rbind(tabla_dist01, dist01$data$sd[[5]]$sd[[4]])
colnames(tabla_dist01) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist01$Distrito <- "1"
tabla_dist01 <- tabla_dist01[,c(8,1,2,3,4)]

tabla_dist02<- data.frame(dist02$data$sd[[1]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[2]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[2]]$sd[[2]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[2]]$sd[[3]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[2]]$sd[[4]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[3]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[3]]$sd[[2]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[4]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[4]]$sd[[2]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[4]]$sd[[3]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[4]]$sd[[4]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[5]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[6]]$sd[[1]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[6]]$sd[[2]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[6]]$sd[[3]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[6]]$sd[[4]])
tabla_dist02<- rbind(tabla_dist02, dist02$data$sd[[7]])
colnames(tabla_dist02) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist02$Distrito <- "2"
tabla_dist02 <- tabla_dist02[,c(8,1,2,3,4)]

tabla_dist03<- data.frame(dist03$data$sd[[1]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[2]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[3]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[3]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[3]]$sd[[3]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[3]]$sd[[4]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[3]]$sd[[5]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[4]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[4]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[5]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[5]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[6]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[6]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[6]]$sd[[3]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[6]]$sd[[4]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[7]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[7]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[8]]$sd[[1]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[8]]$sd[[2]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[8]]$sd[[3]])
tabla_dist03<- rbind(tabla_dist03, dist03$data$sd[[8]]$sd[[4]])
colnames(tabla_dist03) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist03$Distrito <- "3"
tabla_dist03 <- tabla_dist03[,c(8,1,2,3,4)]

tabla_dist04<- data.frame(dist04$data$sd[[1]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[2]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[2]]$sd[[2]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[3]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[4]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[4]]$sd[[2]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[4]]$sd[[3]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[4]]$sd[[4]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[5]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[5]]$sd[[2]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[5]]$sd[[3]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[6]]$sd[[1]])
tabla_dist04<- rbind(tabla_dist04, dist04$data$sd[[6]]$sd[[2]])
colnames(tabla_dist04) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist04$Distrito <- "4"
tabla_dist04 <- tabla_dist04[,c(8,1,2,3,4)]

tabla_dist05<- data.frame(dist05$data$sd[[1]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[2]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[2]]$sd[[2]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[2]]$sd[[3]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[2]]$sd[[4]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[3]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[4]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[5]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[5]]$sd[[2]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[5]]$sd[[3]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[5]]$sd[[4]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[6]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[7]]$sd[[1]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[7]]$sd[[2]])
tabla_dist05<- rbind(tabla_dist05, dist05$data$sd[[8]])
colnames(tabla_dist05) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist05$Distrito <- "5"
tabla_dist05 <- tabla_dist05[,c(8,1,2,3,4)]

tabla_dist06<- data.frame(dist06$data$sd[[1]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[2]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[2]]$sd[[2]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[2]]$sd[[3]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[2]]$sd[[4]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[3]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[4]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[5]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[5]]$sd[[2]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[5]]$sd[[3]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[5]]$sd[[4]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[6]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[7]]$sd[[1]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[7]]$sd[[2]])
tabla_dist06<- rbind(tabla_dist06, dist06$data$sd[[7]]$sd[[3]])
colnames(tabla_dist06) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist06$Distrito <- "6"
tabla_dist06 <- tabla_dist06[,c(8,1,2,3,4)]

tabla_dist07<- data.frame(dist07$data$sd[[1]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[2]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[2]]$sd[[2]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[2]]$sd[[3]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[2]]$sd[[4]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[3]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[4]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[5]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[5]]$sd[[2]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[5]]$sd[[3]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[5]]$sd[[4]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[6]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[7]]$sd[[1]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[7]]$sd[[2]])
tabla_dist07<- rbind(tabla_dist07, dist07$data$sd[[7]]$sd[[3]])
colnames(tabla_dist07) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist07$Distrito <- "7"
tabla_dist07 <- tabla_dist07[,c(8,1,2,3,4)]

tabla_dist08<- data.frame(dist08$data$sd[[1]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[2]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[2]]$sd[[2]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[2]]$sd[[3]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[2]]$sd[[4]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[3]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[4]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[4]]$sd[[2]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[4]]$sd[[3]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[4]]$sd[[4]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[5]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[6]]$sd[[1]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[6]]$sd[[2]])
tabla_dist08<- rbind(tabla_dist08, dist08$data$sd[[6]]$sd[[3]])
colnames(tabla_dist08) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist08$Distrito <- "8"
tabla_dist08 <- tabla_dist08[,c(8,1,2,3,4)]

tabla_dist09<- data.frame(dist09$data$sd[[1]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[2]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[2]]$sd[[2]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[2]]$sd[[3]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[2]]$sd[[4]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[2]]$sd[[5]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[3]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[4]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[4]]$sd[[2]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[4]]$sd[[3]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[5]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[6]]$sd[[1]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[6]]$sd[[2]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[6]]$sd[[3]])
tabla_dist09<- rbind(tabla_dist09, dist09$data$sd[[7]])
colnames(tabla_dist09) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist09$Distrito <- "9"
tabla_dist09 <- tabla_dist09[,c(8,1,2,3,4)]

tabla_dist10<- data.frame(dist10$data$sd[[1]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[2]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[2]]$sd[[2]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[2]]$sd[[3]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[2]]$sd[[4]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[3]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[4]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[4]]$sd[[2]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[4]]$sd[[3]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[4]]$sd[[4]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[5]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[6]]$sd[[1]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[6]]$sd[[2]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[6]]$sd[[3]])
tabla_dist10<- rbind(tabla_dist10, dist10$data$sd[[7]])
colnames(tabla_dist10) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist10$Distrito <- "10"
tabla_dist10 <- tabla_dist10[,c(8,1,2,3,4)]

tabla_dist11<- data.frame(dist11$data$sd[[1]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[2]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[2]]$sd[[2]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[2]]$sd[[3]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[2]]$sd[[4]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[3]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[4]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[4]]$sd[[2]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[4]]$sd[[3]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[5]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[6]]$sd[[1]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[6]]$sd[[2]])
tabla_dist11<- rbind(tabla_dist11, dist11$data$sd[[6]]$sd[[3]])
colnames(tabla_dist11) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist11$Distrito <- "11"
tabla_dist11 <- tabla_dist11[,c(8,1,2,3,4)]

tabla_dist12<- data.frame(dist12$data$sd[[1]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[2]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[2]]$sd[[2]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[2]]$sd[[3]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[2]]$sd[[4]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[3]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[4]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[4]]$sd[[2]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[4]]$sd[[3]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[4]]$sd[[4]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[5]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[6]]$sd[[1]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[6]]$sd[[2]])
tabla_dist12<- rbind(tabla_dist12, dist12$data$sd[[7]])
colnames(tabla_dist12) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist12$Distrito <- "12"
tabla_dist12 <- tabla_dist12[,c(8,1,2,3,4)]

tabla_dist13<- data.frame(dist13$data$sd[[1]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[2]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[2]]$sd[[2]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[2]]$sd[[3]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[3]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[4]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[4]]$sd[[2]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[4]]$sd[[3]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[5]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[6]]$sd[[1]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[6]]$sd[[2]])
tabla_dist13<- rbind(tabla_dist13, dist13$data$sd[[6]]$sd[[3]])
colnames(tabla_dist13) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist13$Distrito <- "13"
tabla_dist13 <- tabla_dist13[,c(8,1,2,3,4)]

tabla_dist14<- data.frame(dist14$data$sd[[1]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[2]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[2]]$sd[[2]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[2]]$sd[[3]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[2]]$sd[[4]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[3]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[4]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[4]]$sd[[2]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[4]]$sd[[3]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[5]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[6]]$sd[[1]])
tabla_dist14<- rbind(tabla_dist14, dist14$data$sd[[6]]$sd[[2]])
colnames(tabla_dist14) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist14$Distrito <- "14"
tabla_dist14 <- tabla_dist14[,c(8,1,2,3,4)]

tabla_dist15<- data.frame(dist15$data$sd[[1]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[2]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[2]]$sd[[2]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[3]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[4]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[5]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[5]]$sd[[2]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[5]]$sd[[3]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[6]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[6]]$sd[[2]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[7]]$sd[[1]])
tabla_dist15<- rbind(tabla_dist15, dist15$data$sd[[7]]$sd[[2]])
colnames(tabla_dist15) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist15$Distrito <- "15"
tabla_dist15 <- tabla_dist15[,c(8,1,2,3,4)]

tabla_dist16<- data.frame(dist16$data$sd[[1]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[2]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[2]]$sd[[2]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[3]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[4]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[5]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[5]]$sd[[2]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[5]]$sd[[3]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[6]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[6]]$sd[[2]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[7]]$sd[[1]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[7]]$sd[[2]])
tabla_dist16<- rbind(tabla_dist16, dist16$data$sd[[8]])
colnames(tabla_dist16) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist16$Distrito <- "16"
tabla_dist16 <- tabla_dist16[,c(8,1,2,3,4)]

tabla_dist17<- data.frame(dist17$data$sd[[1]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[1]]$sd[[2]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[2]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[2]]$sd[[2]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[2]]$sd[[3]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[3]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[4]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[4]]$sd[[2]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[4]]$sd[[3]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[5]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[5]]$sd[[2]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[6]]$sd[[1]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[6]]$sd[[2]])
tabla_dist17<- rbind(tabla_dist17, dist17$data$sd[[6]]$sd[[3]])
colnames(tabla_dist17) <- c("Candidato", "Partido","Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist17$Distrito <- "17"
tabla_dist17 <- tabla_dist17[,c(8,1,2,3,4)]

tabla_dist18<- data.frame(dist18$data$sd[[1]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[1]]$sd[[2]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[2]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[2]]$sd[[2]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[3]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[4]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[4]]$sd[[2]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[4]]$sd[[3]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[5]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[6]]$sd[[1]])
tabla_dist18<- rbind(tabla_dist18, dist18$data$sd[[6]]$sd[[2]])
colnames(tabla_dist18) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist18$Distrito <- "18"
tabla_dist18 <- tabla_dist18[,c(8,1,2,3,4)]

tabla_dist19<- data.frame(dist19$data$sd[[1]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[1]]$sd[[2]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[2]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[2]]$sd[[2]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[2]]$sd[[3]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[3]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[4]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[4]]$sd[[2]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[4]]$sd[[3]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[5]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[6]]$sd[[1]])
tabla_dist19<- rbind(tabla_dist19, dist19$data$sd[[6]]$sd[[2]])
colnames(tabla_dist19) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist19$Distrito <- "19"
tabla_dist19 <- tabla_dist19[,c(8,1,2,3,4)]

tabla_dist20<- data.frame(dist20$data$sd[[1]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[1]]$sd[[2]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[2]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[2]]$sd[[2]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[2]]$sd[[3]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[3]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[4]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[4]]$sd[[2]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[4]]$sd[[3]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[4]]$sd[[4]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[5]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[5]]$sd[[2]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[6]]$sd[[1]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[6]]$sd[[2]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[6]]$sd[[3]])
tabla_dist20<- rbind(tabla_dist20, dist20$data$sd[[7]])
colnames(tabla_dist20) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist20$Distrito <- "20"
tabla_dist20 <- tabla_dist20[,c(8,1,2,3,4)]

tabla_dist21<- data.frame(dist21$data$sd[[1]]$sd[[1]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[2]]$sd[[1]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[2]]$sd[[2]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[2]]$sd[[3]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[3]]$sd[[1]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[3]]$sd[[2]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[3]]$sd[[3]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[3]]$sd[[4]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[4]]$sd[[1]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[5]]$sd[[1]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[5]]$sd[[2]])
tabla_dist21<- rbind(tabla_dist21, dist21$data$sd[[5]]$sd[[3]])
colnames(tabla_dist21) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist21$Distrito <- "21"
tabla_dist21 <- tabla_dist21[,c(8,1,2,3,4)]

tabla_dist22<- data.frame(dist22$data$sd[[1]]$sd[[1]])
tabla_dist22<- rbind(tabla_dist22, dist22$data$sd[[2]]$sd[[1]])
tabla_dist22<- rbind(tabla_dist22, dist22$data$sd[[2]]$sd[[2]])
tabla_dist22<- rbind(tabla_dist22, dist22$data$sd[[3]]$sd[[1]])
tabla_dist22<- rbind(tabla_dist22, dist22$data$sd[[4]]$sd[[1]])
tabla_dist22<- rbind(tabla_dist22, dist22$data$sd[[4]]$sd[[2]])
colnames(tabla_dist22) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist22$Distrito <- "22"
tabla_dist22 <- tabla_dist22[,c(8,1,2,3,4)]

tabla_dist23<- data.frame(dist23$data$sd[[1]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[1]]$sd[[2]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[2]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[3]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[4]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[4]]$sd[[2]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[4]]$sd[[3]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[4]]$sd[[4]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[5]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[6]]$sd[[1]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[6]]$sd[[2]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[6]]$sd[[3]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[7]])
tabla_dist23<- rbind(tabla_dist23, dist23$data$sd[[8]])
colnames(tabla_dist23) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist23$Distrito <- "23"
tabla_dist23 <- tabla_dist23[,c(8,1,2,3,4)]

tabla_dist24<- data.frame(dist24$data$sd[[1]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[2]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[2]]$sd[[2]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[2]]$sd[[3]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[3]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[3]]$sd[[2]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[4]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[4]]$sd[[2]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[4]]$sd[[3]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[5]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[6]]$sd[[1]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[6]]$sd[[2]])
tabla_dist24<- rbind(tabla_dist24, dist24$data$sd[[6]]$sd[[3]])
colnames(tabla_dist24) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist24$Distrito <- "24"
tabla_dist24 <- tabla_dist24[,c(8,1,2,3,4)]

tabla_dist25<- data.frame(dist25$data$sd[[1]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[2]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[3]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[3]]$sd[[2]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[4]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[5]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[5]]$sd[[2]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[5]]$sd[[3]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[6]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[7]]$sd[[1]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[7]]$sd[[2]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[7]]$sd[[3]])
tabla_dist25<- rbind(tabla_dist25, dist25$data$sd[[8]])
colnames(tabla_dist25) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist25$Distrito <- "25"
tabla_dist25 <- tabla_dist25[,c(8,1,2,3,4)]

tabla_dist26<- data.frame(dist26$data$sd[[1]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[2]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[2]]$sd[[2]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[2]]$sd[[3]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[3]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[3]]$sd[[2]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[4]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[5]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[5]]$sd[[2]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[5]]$sd[[3]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[6]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[7]]$sd[[1]])
tabla_dist26<- rbind(tabla_dist26, dist26$data$sd[[7]]$sd[[2]])
colnames(tabla_dist26) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist26$Distrito <- "26"
tabla_dist26 <- tabla_dist26[,c(8,1,2,3,4)]

tabla_dist27<- data.frame(dist27$data$sd[[1]]$sd[[1]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[1]]$sd[[2]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[2]]$sd[[1]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[3]]$sd[[1]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[3]]$sd[[2]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[3]]$sd[[3]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[3]]$sd[[4]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[4]]$sd[[1]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[5]]$sd[[1]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[5]]$sd[[2]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[5]]$sd[[3]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[5]]$sd[[4]])
tabla_dist27<- rbind(tabla_dist27, dist27$data$sd[[6]])
colnames(tabla_dist27) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist27$Distrito <- "27"
tabla_dist27 <- tabla_dist27[,c(8,1,2,3,4)]

tabla_dist28<- data.frame(dist28$data$sd[[1]]$sd[[1]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[2]]$sd[[1]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[3]]$sd[[1]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[3]]$sd[[2]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[3]]$sd[[3]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[3]]$sd[[4]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[4]]$sd[[1]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[5]]$sd[[1]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[5]]$sd[[2]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[5]]$sd[[3]])
tabla_dist28<- rbind(tabla_dist28, dist28$data$sd[[5]]$sd[[4]])
colnames(tabla_dist28) <- c("Candidato", "Partido", "Votos", "Porcentaje", "Candidatos", "Electo")
tabla_dist28$Distrito <- "28"
tabla_dist28 <- tabla_dist28[,c(8,1,2,3,4)]

tabla_diputados<- tabla_dist01
tabla_diputados<- rbind(tabla_diputados,tabla_dist02)
tabla_diputados<- rbind(tabla_diputados,tabla_dist03)
tabla_diputados<- rbind(tabla_diputados,tabla_dist04)
tabla_diputados<- rbind(tabla_diputados,tabla_dist05)
tabla_diputados<- rbind(tabla_diputados,tabla_dist06)
tabla_diputados<- rbind(tabla_diputados,tabla_dist07)
tabla_diputados<- rbind(tabla_diputados,tabla_dist08)
tabla_diputados<- rbind(tabla_diputados,tabla_dist09)
tabla_diputados<- rbind(tabla_diputados,tabla_dist10)
tabla_diputados<- rbind(tabla_diputados,tabla_dist11)
tabla_diputados<- rbind(tabla_diputados,tabla_dist12)
tabla_diputados<- rbind(tabla_diputados,tabla_dist13)
tabla_diputados<- rbind(tabla_diputados,tabla_dist14)
tabla_diputados<- rbind(tabla_diputados,tabla_dist15)
tabla_diputados<- rbind(tabla_diputados,tabla_dist16)
tabla_diputados<- rbind(tabla_diputados,tabla_dist17)
tabla_diputados<- rbind(tabla_diputados,tabla_dist18)
tabla_diputados<- rbind(tabla_diputados,tabla_dist19)
tabla_diputados<- rbind(tabla_diputados,tabla_dist20)
tabla_diputados<- rbind(tabla_diputados,tabla_dist21)
tabla_diputados<- rbind(tabla_diputados,tabla_dist22)
tabla_diputados<- rbind(tabla_diputados,tabla_dist23)
tabla_diputados<- rbind(tabla_diputados,tabla_dist24)
tabla_diputados<- rbind(tabla_diputados,tabla_dist25)
tabla_diputados<- rbind(tabla_diputados,tabla_dist26)
tabla_diputados<- rbind(tabla_diputados,tabla_dist27)
tabla_diputados<- rbind(tabla_diputados,tabla_dist28)

tabla_diputados$Candidato <- sub('....', '', tabla_diputados$Candidato)


xlsx::write.xlsx(filter(tabla_diputados, Distrito == 1),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 1")
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 2),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 2", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 3),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 3", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 4),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 4", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 5),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 5", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 6),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 6", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 7),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 7", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 8),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 8", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 9),  file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 9", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 10), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 10", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 11), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 11", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 12), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 12", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 13), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 13", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 14), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 14", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 15), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 15", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 16), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 16", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 17), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 17", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 18), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 18", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 19), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 19", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 20), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 20", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 21), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 21", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 22), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 22", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 23), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 23", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 24), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 24", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 25), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 25", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 26), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 26", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 27), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 27", append = T)
xlsx::write.xlsx(filter(tabla_diputados, Distrito == 28), file=paste("Votos_candidatos_distritos", sub('...$', '',Sys.time()), ".xlsx", sep=""), row.names=F, sheetName = "Distrito 28", append = T)


